module RecurlyClient.Types.AddOnUpdate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data AddOnUpdate
instance Show AddOnUpdate
instance Eq AddOnUpdate
instance Data.Aeson.FromJSON AddOnUpdate
instance Data.Aeson.ToJSON AddOnUpdate
data AddOnUpdateRevenue_schedule_type
instance Show AddOnUpdateRevenue_schedule_type
instance Eq AddOnUpdateRevenue_schedule_type
instance Data.Aeson.FromJSON AddOnUpdateRevenue_schedule_type
instance Data.Aeson.ToJSON AddOnUpdateRevenue_schedule_type
data AddOnUpdateUsage_calculation_type
instance Show AddOnUpdateUsage_calculation_type
instance Eq AddOnUpdateUsage_calculation_type
instance Data.Aeson.FromJSON AddOnUpdateUsage_calculation_type
instance Data.Aeson.ToJSON AddOnUpdateUsage_calculation_type
