module RecurlyClient.Types.BillingInfoCreate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data BillingInfoCreate
instance Show BillingInfoCreate
instance Eq BillingInfoCreate
instance Data.Aeson.FromJSON BillingInfoCreate
instance Data.Aeson.ToJSON BillingInfoCreate
data BillingInfoCreateAccount_type
instance Show BillingInfoCreateAccount_type
instance Eq BillingInfoCreateAccount_type
instance Data.Aeson.FromJSON BillingInfoCreateAccount_type
instance Data.Aeson.ToJSON BillingInfoCreateAccount_type
data BillingInfoCreateCard_network_preference
instance Show BillingInfoCreateCard_network_preference
instance Eq BillingInfoCreateCard_network_preference
instance Data.Aeson.FromJSON BillingInfoCreateCard_network_preference
instance Data.Aeson.ToJSON BillingInfoCreateCard_network_preference
data BillingInfoCreateCard_type
instance Show BillingInfoCreateCard_type
instance Eq BillingInfoCreateCard_type
instance Data.Aeson.FromJSON BillingInfoCreateCard_type
instance Data.Aeson.ToJSON BillingInfoCreateCard_type
data BillingInfoCreateExternal_hpp_type
instance Show BillingInfoCreateExternal_hpp_type
instance Eq BillingInfoCreateExternal_hpp_type
instance Data.Aeson.FromJSON BillingInfoCreateExternal_hpp_type
instance Data.Aeson.ToJSON BillingInfoCreateExternal_hpp_type
data BillingInfoCreateGateway_attributes
instance Show BillingInfoCreateGateway_attributes
instance Eq BillingInfoCreateGateway_attributes
instance Data.Aeson.FromJSON BillingInfoCreateGateway_attributes
instance Data.Aeson.ToJSON BillingInfoCreateGateway_attributes
data BillingInfoCreateOnline_banking_payment_type
instance Show BillingInfoCreateOnline_banking_payment_type
instance Eq BillingInfoCreateOnline_banking_payment_type
instance Data.Aeson.FromJSON BillingInfoCreateOnline_banking_payment_type
instance Data.Aeson.ToJSON BillingInfoCreateOnline_banking_payment_type
data BillingInfoCreateTax_identifier_type
instance Show BillingInfoCreateTax_identifier_type
instance Eq BillingInfoCreateTax_identifier_type
instance Data.Aeson.FromJSON BillingInfoCreateTax_identifier_type
instance Data.Aeson.ToJSON BillingInfoCreateTax_identifier_type
data BillingInfoCreateTransaction_type
instance Show BillingInfoCreateTransaction_type
instance Eq BillingInfoCreateTransaction_type
instance Data.Aeson.FromJSON BillingInfoCreateTransaction_type
instance Data.Aeson.ToJSON BillingInfoCreateTransaction_type
data BillingInfoCreateType
instance Show BillingInfoCreateType
instance Eq BillingInfoCreateType
instance Data.Aeson.FromJSON BillingInfoCreateType
instance Data.Aeson.ToJSON BillingInfoCreateType
