module RecurlyClient.Types.BillingInfoVerifyCVV where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data BillingInfoVerifyCVV
instance Show BillingInfoVerifyCVV
instance Eq BillingInfoVerifyCVV
instance Data.Aeson.FromJSON BillingInfoVerifyCVV
instance Data.Aeson.ToJSON BillingInfoVerifyCVV
