module RecurlyClient.Types.DunningCampaignsBulkUpdateResponse where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data DunningCampaignsBulkUpdateResponse
instance Show DunningCampaignsBulkUpdateResponse
instance Eq DunningCampaignsBulkUpdateResponse
instance Data.Aeson.FromJSON DunningCampaignsBulkUpdateResponse
instance Data.Aeson.ToJSON DunningCampaignsBulkUpdateResponse
