module RecurlyClient.Types.ErrorMayHaveTransaction where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ErrorMayHaveTransaction
instance Show ErrorMayHaveTransaction
instance Eq ErrorMayHaveTransaction
instance Data.Aeson.FromJSON ErrorMayHaveTransaction
instance Data.Aeson.ToJSON ErrorMayHaveTransaction
data ErrorMayHaveTransactionParams
instance Show ErrorMayHaveTransactionParams
instance Eq ErrorMayHaveTransactionParams
instance Data.Aeson.FromJSON ErrorMayHaveTransactionParams
instance Data.Aeson.ToJSON ErrorMayHaveTransactionParams
data ErrorMayHaveTransactionTransaction_error
instance Show ErrorMayHaveTransactionTransaction_error
instance Eq ErrorMayHaveTransactionTransaction_error
instance Data.Aeson.FromJSON ErrorMayHaveTransactionTransaction_error
instance Data.Aeson.ToJSON ErrorMayHaveTransactionTransaction_error
data ErrorMayHaveTransactionTransaction_errorCategory
instance Show ErrorMayHaveTransactionTransaction_errorCategory
instance Eq ErrorMayHaveTransactionTransaction_errorCategory
instance Data.Aeson.FromJSON ErrorMayHaveTransactionTransaction_errorCategory
instance Data.Aeson.ToJSON ErrorMayHaveTransactionTransaction_errorCategory
data ErrorMayHaveTransactionTransaction_errorCode
instance Show ErrorMayHaveTransactionTransaction_errorCode
instance Eq ErrorMayHaveTransactionTransaction_errorCode
instance Data.Aeson.FromJSON ErrorMayHaveTransactionTransaction_errorCode
instance Data.Aeson.ToJSON ErrorMayHaveTransactionTransaction_errorCode
data ErrorMayHaveTransactionTransaction_errorDecline_code
instance Show ErrorMayHaveTransactionTransaction_errorDecline_code
instance Eq ErrorMayHaveTransactionTransaction_errorDecline_code
instance Data.Aeson.FromJSON ErrorMayHaveTransactionTransaction_errorDecline_code
instance Data.Aeson.ToJSON ErrorMayHaveTransactionTransaction_errorDecline_code
data ErrorMayHaveTransactionType
instance Show ErrorMayHaveTransactionType
instance Eq ErrorMayHaveTransactionType
instance Data.Aeson.FromJSON ErrorMayHaveTransactionType
instance Data.Aeson.ToJSON ErrorMayHaveTransactionType
