module RecurlyClient.Types.ExternalProductReferenceBase where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ExternalProductReferenceBase
instance Show ExternalProductReferenceBase
instance Eq ExternalProductReferenceBase
instance Data.Aeson.FromJSON ExternalProductReferenceBase
instance Data.Aeson.ToJSON ExternalProductReferenceBase
data ExternalProductReferenceBaseExternal_connection_type
instance Show ExternalProductReferenceBaseExternal_connection_type
instance Eq ExternalProductReferenceBaseExternal_connection_type
instance Data.Aeson.FromJSON ExternalProductReferenceBaseExternal_connection_type
instance Data.Aeson.ToJSON ExternalProductReferenceBaseExternal_connection_type
