module RecurlyClient.Types.ExternalProductReferenceCreate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ExternalProductReferenceCreate
instance Show ExternalProductReferenceCreate
instance Eq ExternalProductReferenceCreate
instance Data.Aeson.FromJSON ExternalProductReferenceCreate
instance Data.Aeson.ToJSON ExternalProductReferenceCreate
data ExternalProductReferenceCreateExternal_connection_type
instance Show ExternalProductReferenceCreateExternal_connection_type
instance Eq ExternalProductReferenceCreateExternal_connection_type
instance Data.Aeson.FromJSON ExternalProductReferenceCreateExternal_connection_type
instance Data.Aeson.ToJSON ExternalProductReferenceCreateExternal_connection_type
