module RecurlyClient.Types.ExternalProductReferenceCollection where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ExternalProductReferenceCollection
instance Show ExternalProductReferenceCollection
instance Eq ExternalProductReferenceCollection
instance Data.Aeson.FromJSON ExternalProductReferenceCollection
instance Data.Aeson.ToJSON ExternalProductReferenceCollection
