module RecurlyClient.Types.ExternalProductReferenceCreate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ExternalProductReferenceCreate
instance Show ExternalProductReferenceCreate
instance Eq ExternalProductReferenceCreate
instance Data.Aeson.FromJSON ExternalProductReferenceCreate
instance Data.Aeson.ToJSON ExternalProductReferenceCreate
