module RecurlyClient.Types.ShippingMethodUpdate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data ShippingMethodUpdate
instance Show ShippingMethodUpdate
instance Eq ShippingMethodUpdate
instance Data.Aeson.FromJSON ShippingMethodUpdate
instance Data.Aeson.ToJSON ShippingMethodUpdate
