module RecurlyClient.Types.SubscriptionAddOnCreate where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data SubscriptionAddOnCreate
instance Show SubscriptionAddOnCreate
instance Eq SubscriptionAddOnCreate
instance Data.Aeson.FromJSON SubscriptionAddOnCreate
instance Data.Aeson.ToJSON SubscriptionAddOnCreate
data SubscriptionAddOnCreateAdd_on_source
instance Show SubscriptionAddOnCreateAdd_on_source
instance Eq SubscriptionAddOnCreateAdd_on_source
instance Data.Aeson.FromJSON SubscriptionAddOnCreateAdd_on_source
instance Data.Aeson.ToJSON SubscriptionAddOnCreateAdd_on_source
data SubscriptionAddOnCreateRevenue_schedule_type
instance Show SubscriptionAddOnCreateRevenue_schedule_type
instance Eq SubscriptionAddOnCreateRevenue_schedule_type
instance Data.Aeson.FromJSON SubscriptionAddOnCreateRevenue_schedule_type
instance Data.Aeson.ToJSON SubscriptionAddOnCreateRevenue_schedule_type
