module RecurlyClient.Types.SubscriptionAddOn where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data SubscriptionAddOn
instance Show SubscriptionAddOn
instance Eq SubscriptionAddOn
instance Data.Aeson.FromJSON SubscriptionAddOn
instance Data.Aeson.ToJSON SubscriptionAddOn
data SubscriptionAddOnAdd_on_source
instance Show SubscriptionAddOnAdd_on_source
instance Eq SubscriptionAddOnAdd_on_source
instance Data.Aeson.FromJSON SubscriptionAddOnAdd_on_source
instance Data.Aeson.ToJSON SubscriptionAddOnAdd_on_source
data SubscriptionAddOnRevenue_schedule_type
instance Show SubscriptionAddOnRevenue_schedule_type
instance Eq SubscriptionAddOnRevenue_schedule_type
instance Data.Aeson.FromJSON SubscriptionAddOnRevenue_schedule_type
instance Data.Aeson.ToJSON SubscriptionAddOnRevenue_schedule_type
data SubscriptionAddOnTier_type
instance Show SubscriptionAddOnTier_type
instance Eq SubscriptionAddOnTier_type
instance Data.Aeson.FromJSON SubscriptionAddOnTier_type
instance Data.Aeson.ToJSON SubscriptionAddOnTier_type
data SubscriptionAddOnUsage_calculation_type
instance Show SubscriptionAddOnUsage_calculation_type
instance Eq SubscriptionAddOnUsage_calculation_type
instance Data.Aeson.FromJSON SubscriptionAddOnUsage_calculation_type
instance Data.Aeson.ToJSON SubscriptionAddOnUsage_calculation_type
data SubscriptionAddOnUsage_timeframe
instance Show SubscriptionAddOnUsage_timeframe
instance Eq SubscriptionAddOnUsage_timeframe
instance Data.Aeson.FromJSON SubscriptionAddOnUsage_timeframe
instance Data.Aeson.ToJSON SubscriptionAddOnUsage_timeframe
