module RecurlyClient.Types.SubscriptionAddOnPercentageTier where
import qualified Data.Aeson
import qualified RecurlyClient.Common
data SubscriptionAddOnPercentageTier
instance Show SubscriptionAddOnPercentageTier
instance Eq SubscriptionAddOnPercentageTier
instance Data.Aeson.FromJSON SubscriptionAddOnPercentageTier
instance Data.Aeson.ToJSON SubscriptionAddOnPercentageTier
